import styles from "./index.module.scss";

import { useRouter } from "next/router";
import Head from "next/head";

import ChatSidebar from "@/components/chatSidebar/Index";
import TitleBar from "@/components/TitleBar";
import MessagesList from "@/components/MessagesList/Index";
import Login from "@/components/Login";

import { auth } from "@/firebase";
import { useAuthState } from "react-firebase-hooks/auth";

export default function () {
  const router = useRouter();
  const db_name = router.query.dbname;
  console.log("in db name:", db_name);
  console.log("log query:", router.query);
  const [user] = useAuthState(auth);

  return (
    <>
      {!user ? (
        <Login />
      ) : (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.leftSide}>
              <ChatSidebar />
            </div>
            <div className={styles.rightSide}>
              <TitleBar title={db_name} />
              {db_name && <MessagesList dbname={db_name} />}
            </div>
          </main>
        </>
      )}
    </>
  );
}
