import styles from "./index.module.scss";

import { useRouter } from "next/router";
import Head from "next/head";

import ChatSidebar from "@/components/chatSidebar/Index";
import TitleBar from "@/components/TitleBar";
import MessagesList from "@/components/MessagesList/Index";
import Login from "@/components/Login";

import { auth } from "@/firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import { useState } from "react";

export default function () {
  const router = useRouter();
  const db_name = router.query.dbname;
  const [user] = useAuthState(auth);

  const [node, setNode] = useState({});

  console.log("HAI APERTO LA CHAT CON ", node);

  //TODO: CONTROLLO: SE QUALCUNO CERCA /private BISOGNA VERIFICARE CHE CI SIA IL NODE
  return (
    <>
      {!user ? (
        <Login />
      ) : (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.leftSide}>
              <ChatSidebar node={node} setNode={setNode} />
            </div>
            <div className={styles.rightSide}>
              {db_name === "private" ? (
                node.otherUser ? (
                  <>
                    <TitleBar
                      setNode={setNode}
                      title={node.otherUser.displayName}
                      photo={node.otherUser.photoURL}
                    />
                    <MessagesList dbname={node.node} privateChat={true} />
                  </>
                ) : (
                  <>
                    <h1>CHAT PRIVATA NUOVA</h1>
                  </>
                )
              ) : (
                <>
                  <TitleBar title={db_name} setNode={setNode} />
                  {db_name && (
                    <MessagesList dbname={db_name} privateChat={false} />
                  )}
                </>
              )}
              {/* {db_name === "private" && node.otherUser ? (
                <TitleBar title={node.otherUser.displayName} />
              ) : (
                <h1>ERRORE</h1>
              )} */}
              {/* {db_name && <MessagesList dbname={db_name} />} */}
            </div>
          </main>
        </>
      )}
    </>
  );
}
